# Generated by Django 4.0.3 on 2022-04-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='baths',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='garages',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(null=True),
        ),
    ]
