# Generated by Django 4.0.3 on 2022-04-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_property_area_property_baths_property_garages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='area',
        ),
    ]
