# Generated by Django 4.0.3 on 2022-04-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_property_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='image4',
            new_name='bathroomimage4',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='image5',
            new_name='bedroomimage5',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='image1',
            new_name='houseimage1',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='image3',
            new_name='kitchenimage3',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='image2',
            new_name='livingroomimage2',
        ),
    ]
