# Generated by Django 4.0.3 on 2022-04-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_image4_property_bathroomimage4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='amenity1',
            field=models.CharField(blank=True, default='24/7 security/cctv cameras.', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenity2',
            field=models.CharField(blank=True, default='silent estate', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenity3',
            field=models.CharField(blank=True, default='Backup generator', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenity4',
            field=models.CharField(blank=True, default='Kindergatten availableKindergatten available', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenity5',
            field=models.CharField(blank=True, default='Supermarket', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenity6',
            field=models.CharField(blank=True, default='Reserved water', max_length=200),
        ),
    ]
