# Generated by Django 4.0.3 on 2022-04-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_property_baths_alter_property_garages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(default='Nairobi', max_length=250, null=True),
        ),
    ]
