# Generated by Django 4.0.3 on 2022-04-21 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_property_videolink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='videolink',
            field=models.TextField(default='https://player.vimeo.com/video/73221098', validators=[django.core.validators.URLValidator()]),
        ),
    ]
